In [2]:
import numpy as np
from numpy.linalg import eig

In [3]:
P = np.array([[0.4, 0.5, 0.1], [0.05, 0.7, 0.25], [0.05, 0.5, 0.45]])

In [4]:
w, v = eig(P.T)

In [15]:
w

array([1.  , 0.35, 0.2 ])

In [21]:
pi = v[:, 0]

In [26]:
pi @ P

array([0.11041049, 0.89708523, 0.42784065])

In [27]:
pi

array([0.11041049, 0.89708523, 0.42784065])